name: App:Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: ./.github/actions
      - name: Running tests
        run: sh ./scripts/run-test.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
