name: App:Main
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize tests
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: ./.github/actions
      - name: Running tests
        run: |
          flutter clean
          flutter pub get
          sh ./scripts/run-test.sh
          echo "ğŸ This job's status is ${{ job.status }}."
